apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: istilgangskontroll
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    timeout: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /internal/metrics
  ingresses:
    - "https://istilgangskontroll.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: isaktivitetskrav
        - application: isarbeidsuforhet
        - application: isbehandlerdialog
        - application: isdialogmelding
        - application: isdialogmote
        - application: isdialogmotekandidat
        - application: isfrisktilarbeid
        - application: ishuskelapp
        - application: ismeroppfolging
        - application: isnarmesteleder
        - application: isoppfolgingstilfelle
        - application: ispengestopp
        - application: ispersonoppgave
        - application: fastlegerest
        - application: finnfastlege
        - application: syfobehandlendeenhet
        - application: syfomodiaperson
        - application: syfooversiktsrv
        - application: syfoperson
        - application: esyfovarsel
          namespace: team-esyfo
          cluster: prod-gcp
        - application: syfomotebehov
          namespace: team-esyfo
          cluster: prod-fss
        - application: syfomotebehov
          namespace: team-esyfo
          cluster: prod-gcp
        - application: syfooppfolgingsplanservice
          namespace: team-esyfo
          cluster: prod-fss
        - application: lps-oppfolgingsplan-mottak
          namespace: team-esyfo
          cluster: prod-gcp
        - application: meroppfolging-backend
          namespace: team-esyfo
        - application: oppfolgingsplan-backend
          namespace: team-esyfo
        - application: spinnsyn-backend
          namespace: flex
          cluster: prod-gcp
        - application: sykepengesoknad-backend
          namespace: flex
          cluster: prod-gcp
        - application: smregistrering-backend
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: syfosmmanuell-backend
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: syfosmregister
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: syk-dig-backend
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: sykepengedager-informasjon
          namespace: team-esyfo
    outbound:
      external:
        - host: "axsys.prod-fss-pub.nais.io"
        - host: "graph.microsoft.com"
        - host: "pdl-pip-api.prod-fss-pub.nais.io"
        - host: "audit.nais"
          ports:
            - port: 6514
      rules:
        - application: istilgangskontroll-redis
        - application: syfobehandlendeenhet
        - application: skjermede-personer-pip
          namespace: nom
        - application: norg2
          namespace: org
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  envFrom:
    - secret: istilgangskontroll-redis-password
  env:
    - name: AXSYS_URL
      value: "https://axsys.prod-fss-pub.nais.io"
    - name: AXSYS_CLIENT_ID
      value: "prod-fss.org.axsys"
    - name: GRAPHAPI_URL
      value: "https://graph.microsoft.com"
    - name: NORG2_URL
      value: "http://norg2.org"
    - name: PDL_CLIENT_ID
      value: "prod-fss.pdl.pdl-pip-api"
    - name: PDL_URL
      value: "https://pdl-pip-api.prod-fss-pub.nais.io"
    - name: SYFOBEHANDLENDEENHET_CLIENT_ID
      value: "prod-gcp.teamsykefravr.syfobehandlendeenhet"
    - name: SYFOBEHANDLENDEENHET_URL
      value: "http://syfobehandlendeenhet"
    - name: SKJERMEDE_PERSONER_CLIENT_ID
      value: "prod-gcp.nom.skjermede-personer-pip"
    - name: SKJERMEDE_PERSONER_URL
      value: "http://skjermede-personer-pip.nom"
    - name: REDIS_HOST
      value: "istilgangskontroll-redis"

    - name: ROLE_KODE6_ID
      value: "ad7b87a6-9180-467c-affc-20a566b0fec0" # 0000-GA-Strengt_Fortrolig_Adresse
    - name: ROLE_KODE7_ID
      value: "9ec6487d-f37a-4aad-a027-cd221c1ac32b" # 0000-GA-Fortrolig_Adresse
    - name: ROLE_SYFO_ID
      value: "100e88eb-79af-4136-8bfe-f79b32021f43" # 0000-GA-SYFO-SENSITIV
    - name: ROLE_SKJERMING_ID
      value: "e750ceb5-b70b-4d94-b4fa-9d22467b786b" # 0000-GA-Egne_ansatte
    - name: ROLE_NASJONAL_ID
      value: "3063daf5-24c6-409c-9139-2d843cb4327b" # 0000-GA-GOSYS_NASJONAL
    - name: ROLE_REGIONAL_ID
      value: "422852aa-aad5-4601-a8c8-917ef42b6601" # 0000-GA-GOSYS_REGIONAL
    - name: ROLE_PAPIRSYKMELDING_ID
      value: "dfde2123-1969-4cd2-8977-bdf19721e76d" # 0000-GA-papirsykmelding
