apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: istilgangskontroll
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    timeout: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /internal/metrics
  ingresses:
    - "https://istilgangskontroll.intern.dev.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: isaktivitetskrav
        - application: isarbeidsuforhet
        - application: isbehandlerdialog
        - application: isdialogmelding
        - application: isdialogmote
        - application: isdialogmotekandidat
        - application: isfrisktilarbeid
        - application: ishuskelapp
        - application: ismeroppfolging
        - application: isnarmesteleder
        - application: isoppfolgingstilfelle
        - application: ispengestopp
        - application: ispersonoppgave
        - application: fastlegerest
        - application: finnfastlege
        - application: syfobehandlendeenhet
        - application: syfomodiaperson
        - application: syfooversiktsrv
        - application: syfoperson
        - application: esyfovarsel
          namespace: team-esyfo
          cluster: dev-gcp
        - application: syfomotebehov
          namespace: team-esyfo
          cluster: dev-fss
        - application: syfomotebehov
          namespace: team-esyfo
          cluster: dev-gcp
        - application: syfooppfolgingsplanservice
          namespace: team-esyfo
          cluster: dev-fss
        - application: lps-oppfolgingsplan-mottak
          namespace: team-esyfo
          cluster: dev-gcp
        - application: meroppfolging-backend
          namespace: team-esyfo
        - application: oppfolgingsplan-backend
          namespace: team-esyfo
        - application: spinnsyn-backend
          namespace: flex
          cluster: dev-gcp
        - application: sykepengesoknad-backend
          namespace: flex
          cluster: dev-gcp
        - application: smregistrering-backend
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: syfosmmanuell-backend
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: syfosmregister
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: syk-dig-backend
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: sykepengedager-informasjon
          namespace: team-esyfo
    outbound:
      external:
        - host: "axsys.dev-fss-pub.nais.io"
        - host: "norg2.dev-fss-pub.nais.io"
        - host: "graph.microsoft.com"
        - host: "pdl-pip-api.dev-fss-pub.nais.io"
        - host: "audit.nais"
          ports:
            - port: 6514
      rules:
        - application: istilgangskontroll-redis
        - application: syfobehandlendeenhet
        - application: skjermede-personer-pip
          namespace: nom
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  envFrom:
    - secret: istilgangskontroll-redis-password
  env:
    - name: AXSYS_URL
      value: "https://axsys.dev-fss-pub.nais.io"
    - name: AXSYS_CLIENT_ID
      value: "dev-fss.org.axsys"
    - name: GRAPHAPI_URL
      value: "https://graph.microsoft.com"
    - name: NORG2_URL
      value: "https://norg2.dev-fss-pub.nais.io"
    - name: PDL_CLIENT_ID
      value: "dev-fss.pdl.pdl-pip-api"
    - name: PDL_URL
      value: "https://pdl-pip-api.dev-fss-pub.nais.io"
    - name: SYFOBEHANDLENDEENHET_CLIENT_ID
      value: "dev-gcp.teamsykefravr.syfobehandlendeenhet"
    - name: SYFOBEHANDLENDEENHET_URL
      value: "http://syfobehandlendeenhet"
    - name: SKJERMEDE_PERSONER_CLIENT_ID
      value: "dev-gcp.nom.skjermede-personer-pip"
    - name: SKJERMEDE_PERSONER_URL
      value: "http://skjermede-personer-pip.nom"
    - name: REDIS_HOST
      value: "istilgangskontroll-redis"

    - name: ROLE_KODE6_ID
      value: "5ef775f2-61f8-4283-bf3d-8d03f428aa14" # 0000-GA-Strengt_Fortrolig_Adresse
    - name: ROLE_KODE7_ID
      value: "ea930b6b-9397-44d9-b9e6-f4cf527a632a" # 0000-GA-Fortrolig_Adresse
    - name: ROLE_SYFO_ID
      value: "c8957e0a-909c-4b62-8e11-93aae6d295e6" # 0000-GA-SYFO-SENSITIV
    - name: ROLE_SKJERMING_ID
      value: "dbe4ad45-320b-4e9a-aaa1-73cca4ee124d" # 0000-GA-Egne_ansatte
    - name: ROLE_NASJONAL_ID
      value: "924badcd-b936-44f4-b7bf-97c03de0893a" # 0000-GA-GOSYS_NASJONAL
    - name: ROLE_REGIONAL_ID
      value: "d2987104-63b2-4110-83ac-20ff6afe24a2" # 0000-GA-GOSYS_REGIONAL
    - name: ROLE_PAPIRSYKMELDING_ID
      value: "16aff429-1efc-402a-ae12-4000633d0063" # 0000-GA-papirsykmelding
