apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: teamsykefravr
  annotations:
    "nais.io/run-as-group": "0"
    "nais.io/read-only-file-system": "false"
  namespace: teamsykefravr
  name: istilgangskontroll-redis
spec:
  image: bitnami/redis:7.0.11
  port: 6379
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi
  service:
    port: 6379
    protocol: redis
  accessPolicy:
    inbound:
      rules:
        - application: istilgangskontroll
        - application: istilgangskontroll-redisexporter
  envFrom:
    - secret: istilgangskontroll-redis-password
