name: aiven-redis

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/aiven-redis.yaml'
      - '.nais/redis/**'

permissions:
  id-token: write

jobs:
  deploy-redis-dev:
    name: Deploy Aiven Redis dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy Aiven Redis dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/redis/aiven-redis.yaml
          VARS: .nais/redis/dev.json

  deploy-redis-prod:
    name: Deploy Aiven Redis prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy Aiven Redis prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/redis/aiven-redis.yaml
          VARS: .nais/redis/prod.json
